Check interval decreased to 4, ping message disabled and replaced by sympler

diff --git a/recscr b/recscr
--- a/recscr
+++ b/recscr
@@ -2,6 +2,10 @@
 
 while true
 do
-	ping -c 1 www.google.com || ifconfig eth0 down	
-	sleep 7
+	echo "Network check"
+	ping -c 1 www.google.com &> /dev/null || (
+		echo "Network check failed, reconnecting"
+		ifconfig eth0 down
+	)
+	sleep 4
 done
